/* SQLEditor (MySQL (2))*/

CREATE TABLE IF NOT EXISTS user_type
(
id int(11) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name varchar(64) COLLATE utf8_unicode_ci NOT NULL,
value SMALLINT(6) UNSIGNED NOT NULL UNIQUE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS gender
(
id SMALLINT(6) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name varchar(64) COLLATE utf8_unicode_ci NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS status
(
id int(11) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name varchar(64) COLLATE utf8_unicode_ci NOT NULL,
value SMALLINT(6) UNSIGNED NOT NULL UNIQUE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS role
(
id int(11) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
name varchar(64) COLLATE utf8_unicode_ci NOT NULL,
value SMALLINT(6) UNSIGNED NOT NULL UNIQUE,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS profile
(
id int(11) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
user_id int(11) UNSIGNED NOT NULL UNIQUE,
given_name varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
family_name varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
birth_date DATE DEFAULT NULL,
gender_id SMALLINT(6) UNSIGNED DEFAULT 0 NOT NULL,
created_at DATETIME NOT NULL,
updated_at DATETIME NOT NULL,
PRIMARY KEY (id)
) ENGINE=InnoDB CHARACTER SET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE profile ADD FOREIGN KEY gender_id_idxfk (gender_id) REFERENCES gender (id);
